### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by serepo** [tuukkalai/ot-harjoitustyo#1]
**Koodikatselmointi, matopeli. Ladattu 8.12.2020 klo 18.30**

Idea on hyvä ja käyttöliittymä selkeä. Ohjelma oli jo melkein viikon vanha kun kloonasin sen, joten olet varmaan jo ehtinyt kehittää sitä paljon eteenpäin.

Käyttöliittymässä en huomannut mitään erityisiä ongelmia. Tässä kuitenkin muutamia huomioita: 
- käyttäjän näkökulmasta olisi hyvä jos peli olisi mahdollista pausettaa vaikka painamalla välilyöntiä. Tällöin olisi lisäksi ehkä tarpeen, että pelissä olisi vaikka aloitusnäkymässä näkyvissä siinä käytettävät kontrollit.
- haastavuutta tai pelin kestoa voisi lisätä se, jos pelikenttä voisi olla mielivaltaisen kokoinen, vaikka se ei tietenkään alkuperäisen pelin hengen mukaista.
- peli voisi ulkoasultaan (eli käytännössä kentän väriltä) olla vastaava kuin alkuperäinen.

Koodi taas näyttää selkeältä ja siistiltä. Kurssin käytänteiden mukaan käyttöliittymäkoodista voisi kuitenkin ehkä eriyttää Snake-luokan ja siihen liittyvän toiminnallisuuden (värin ja koordinaattien asetus) erilliseen tiedostoon.

Koodiin liittyvänä huomiona: ilmeisesti madon kuuluisi muodostua kolmesta peräkkäisestä laatikosta, mutta ensimmäinen aika-askel tuo laatikot samaan kasaan. Jos asettaa tick-metodin switch-casen muuttamaan koordinaatteja yhden käärmeneliön sivunpituudella tai vähän yli, mato liikkuu toivotummalla tavalla ja näyttää paremmalta. Tämän olet varmaan tosin jo huomannutkin tässä viikon aikana.

Ehkä vähän liian laaja kehitysehdotus enää tässä vaiheessa, mutta tuli mieleen, voisiko koko pelikenttä olla iso gridi, jossa madon jokainen pala liikkuu aina tämän gridin solusta toiseen? Vähän vastaavasti, kuin nytkin liikutat paloja. Tällöin olisi helppoa määritellä jatkossa se hetki, millon mato syö saaliin ja kasvaa tai milloin mato osuu itseensä, ja lisäksi madon liikkuminen kentän ympäri voi olla tällöin myös helpompi toteuttaa.

Kaiken kaikkiaan peli näyttää olevan oikein hyvässä vaiheessa, eikä muita ongelmia käärmeen liikkumisen lisäksi löytynyt.

**Comment by tuukkalai** [comment]
Kiitos kommeteista!
Madon liike saatu korjattua. Gridi toteutus huomioitu ja hieman vastaavaa rakennetta onkin tarkoitus hakea. Ei kuitenkaan moniulotteisena taulukkona, vaan eri komponenttien koordinaatteina.
Ennen viimeista palautusta tulisikin saada sovelluksen koodi refaktoroitua kurssin käytänteiden mukaiseksi.
