### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by shiftleino** [tuukkalai/ot-harjoitustyo#1]
Projekti ladattu itselle: 10.12.2021 klo 13:30

Ihan ensiksi hienoa työtä! Projekti on edennyt mallikkaasti ja varsinkin projektin dokumentaation on hyvin kattavaa. Työssä käytetään monia hyviä ohjelmointitapoja ja pystyin itsekin oppimaan uutta tutustuessani projektisi koodiin. Erityisesti pidän tavastasi tehdä jokaiselle virheilmoitukselle oma Exception, voisin itse ottaa tämän käyttöön myös omaan projektiini. 

Ohjelmassa on joitain pieniä bugeja vielä, esimerkiksi kun käyttäjä kirjautuessaan sovellukseen, jossa on vain "ohje-entry", poistaa tämän ohje-entryn, sovellus kaatuu ja esittää virheilmoituksen terminaaliin: "UnboundLocalError: local variable 'entry' referenced before assignment". Lisäksi kirjautuessa seuraavalla kerralla tälle käyttäjälle, ohjelma kaatuu automaattisesti. Sama tapahtuu aina kun kaikki entryt poistaa. Tähän voisi tehdä esimerkiksi ratkaisun, jossa Delete-nappi ei ole käytössä ennen kuin muita entryjä on luotu. 

Muita bugeja en omilla kokeiluillani löytänyt. Ohjelman koodista ei löytynyt paljoa parannettavaa, sillä se noudatti mielestäni hyvän ohjelmoinnin periaatteita. User-olion omat attribuutit voisi laittaa ehkä self.__ (name mangling), mutta taas en tiedä mikä on HY:llä käytäntö näissä (oma tausta eri yliopistosta). Tkinterin funktioihin en pysty kommentoida, sillä kyseinen kirjasto ei ole minulle tuttu.

Lopuksi vielä joitain parannusehdotuksia, jotka voivat olla enemmänkin makuasioita. Yrittäessä kirjautua sovellukseen tyhjillä kentillä sovellus voisi ilmoittaa tästä käyttäjälle jotenkin erilailla kuin väärää käyttäjätunnusta käytettäessä (tällä hetkellä: "Username '' not found").

**Comment by tuukkalai** [comment]
Kiitos kommenteista!
Bugi korjattu viimeisimmässä releasessä, samoin virheviestejä muokattu.
Olioiden attribuuttien näkyvyyksiä tarkistan projektin edetessä. Monissa luokissa on vain suuntaa antavasti lisätty joko yksi tai kaksi alaviivaa attributuin eteen, merkaten onko alustavassa ajatuksessa tarkoitus päästä attribuuttiin käsiksi.
Tsemppiä kurssin jatkoon!
